### ISSUE TITLE
Incorrect position stored for hidden neurons

### ISSUE THREAD

**Issue by ElteHupkes** [jauerb/robogen#51]
In `Robot::decodeBrain()`, line 381 of `Robot.cpp` (https://github.com/jauerb/robogen/blob/master/src/Robot.cpp#L381), the index of the hidden neuron is added to the `hiddenNeuronIds` map. However, the counter for output neurons is used rather than the counter for hidden neurons, causing any hidden neuron position to be calculated incorrectly when connection weights are assigned later on.

My apologies for not having the time to create a pull request at this point, but I believe the line should be changed to:

```c++
hiddenNeuronIds.insert(ioPair(neuron.id(),nHidden));
```

**Comment by jauerb** [comment]
I think you are correct, let me verify and make the change.

Thanks!
