### ISSUE TITLE
Your website broke down

### ISSUE THREAD

**Issue by shenwuyue-xie** [jauerb/robogen#68]
[http://robogen.org/](url)
Neither this URL nor the corresponding URL can be opened

**Comment by jauerb** [comment]
It should be back up now.

**Comment by daydin** [comment]
Hi Josh,

Hope this email finds you well. Do you mind taking me of the email
notifications?

Deniz

**Comment by loshchil** [comment]
Hi Deniz,

You can click https://github.com/lis-epfl/robogen/issues/68 and then
"unwatch -> not watching" button.

Ilya
